# Generated by Django 2.2.1 on 2019-05-31 00:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20190530_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='post',
            name='house_pic',
            field=models.ImageField(blank=True, upload_to='house_pic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 31, 0, 12, 28, 454706, tzinfo=utc)),
        ),
    ]
